version: "3"
services:
  icarus:
    build: .
    container_name: icarus
    hostname: icarus
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "17777:17777/udp"
      - "27015:27015/udp"
    volumes:
      - ./data:/home/icarus/.wine/drive_c/icarus
      - ./game:/opt/icarus
    environment:
      - SERVER_NAME=MornedhelsTest
      - PORT=17777
      - QUERYPORT=27015
      - PUID=501
      - PGID=501
      - UPDATE_CRON=*/30 * * * *
      - CLEANUP_CRON=*/10 * * * *
