#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

pidfile=$icarus_updater_pidfile
latest_version=-1

main() {
  info "Running icarus-updater"
  update
  info "icarus-updater complete"
}

update() {
  if [ -f "$pidfile" ]; then
    info "Found existing PID file - checking process"
    checkLock $pidfile
  fi
  trap shutdown SIGINT SIGTERM
  if ! checkForUpdates; then
    if ! checkRunning "icarus-server"; then
      info "ICARUS server is not running - starting"
      supervisorctl start icarus-server
    fi
    return
  fi
  if ! checkServerEmpty; then
    warn "ICARUS server is not empty - update will not be performed"
    return
  fi

  doUpdate &
  icarus_updater_pid=$!
  echo $icarus_updater_pid >"$pidfile"
  wait $icarus_updater_pid
}

doUpdate() {
  updatePreHook
  if checkRunning "icarus-server"; then
    supervisorctl stop icarus-server
  fi
  verifyCpuMhz
  downloadIcarus
  if ! downloadIcarus; then
    warn "Download of ICARUS server failed - aborting update"
    supervisorctl start icarus-server
    clearLock "$pidfile"
    return
  fi
  setCurrentVersion
  supervisorctl start icarus-server
  updatePostHook

  clearLock "$pidfile"
}

downloadIcarus() {
  $steamcmd_path +@sSteamCmdForcePlatformType windows +force_install_dir "$install_path" +login anonymous +app_update $steam_app_id $STEAMCMD_ARGS +quit
}

# This works around the `Unable to determine CPU Frequency. Try defining CPU_MHZ.` steamcmd issue.
verifyCpuMhz() {
  local float_regex
  local cpu_mhz
  float_regex="^([0-9]+\\.?[0-9]*)\$"
  cpu_mhz=$(grep "^cpu MHz" /proc/cpuinfo | head -1 | cut -d : -f 2 | xargs)
  if [ -n "$cpu_mhz" ] && [[ "$cpu_mhz" =~ $float_regex ]] && [ "${cpu_mhz%.*}" -gt 0 ]; then
    debug "Found CPU with $cpu_mhz MHz"
    unset CPU_MHZ
  else
    debug "Unable to determine CPU Frequency - setting a default of 1.5 GHz so steamcmd won't complain"
    export CPU_MHZ="1500.000"
  fi
}

checkForUpdates() {
  local current_version
  if [ -f "$version_file_path" ]; then
    current_version=$(cat "$version_file_path")
  else
    current_version="0"
  fi

  latest_version=$(curl -sX GET "https://api.steamcmd.net/v1/info/$steam_app_id" | jq -r ".data.\"$steam_app_id\".depots.branches.$GAME_BRANCH.buildid")

  if [ "$latest_version" == "null" ] || [ "$latest_version" == "-1" ]; then
    if [ "$current_version" == "0" ]; then
      warn "Unable to determine latest version of icarus server! No version currently installed, update server anyways"
      return 0
    fi
    warn "Unable to determine latest version of icarus server! No update will be performed"
    return 1
  fi

  if [ "$current_version" != "$latest_version" ]; then
    info "ICARUS server needs to be updated"
    return 0
  else
    info "ICARUS server is already the latest version"
    return 1
  fi
}

checkServerEmpty() {
  local connected_players

  if [ -n "$STEAM_API_PUBLIC_IP" ] && [ -n "$STEAM_API_KEY" ]; then
    warn "STEAM_API_KEY are deprecated and will be removed in a future release"
  else
    if [ "$UPDATE_CHECK_PLAYERS" == "false" ]; then
      return 0
    fi
  fi

  connected_players=$(python3 -c "
try:
    import a2s
    print(len(a2s.players(('127.0.0.1',${SERVER_QUERYPORT:-15637}))))
except Exception as e:
    print('null')
")

  debug "[checkServerEmpty] connected_players: $connected_players"
  if [ -n "$connected_players" ] && [ "$connected_players" != "null" ] && [ "$connected_players" -gt 0 ]; then
    return 1
  fi

  return 0
}

setCurrentVersion() {
  if [ "$latest_version" == "null" ] || [ "$latest_version" == "-1" ]; then
    warn "Unable to set current version - latest version is unknown"
    warn "Next update check will restart the server until version can be determined"
    return 1
  fi
  echo "$latest_version" >"$version_file_path"
}


updatePreHook() {
  if [ -n "$UPDATE_PRE_HOOK" ]; then
    info "Running update pre hook: $UPDATE_PRE_HOOK"
    eval "$UPDATE_PRE_HOOK"
  fi
}

updatePostHook() {
  if [ -n "$UPDATE_POST_HOOK" ]; then
    info "Running update post hook: $UPDATE_POST_HOOK"
    eval "$UPDATE_POST_HOOK"
  fi
}

shutdown() {
  debug "Received signal to shut down icarus-updater"
  clearLock "$pidfile"
}

main
