#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

main() {
  info "Running icarus-cleanup"
  cleanupProspects
  info "Cleanup complete"
  exit 0
}

function cleanupProspects {
  local prospectFiles
  local OIFS
  local IFS
  OIFS="$IFS"
  IFS=$'\n'
  prospectFiles=$(find $data_path/Saved/PlayerData/DedicatedServer/Prospects -name '*.json')
  for prospect in $prospectFiles; do
    # skips prospect if it is included in the regex CLEANUP_EXCLUDES
    if [[ $prospect =~ $CLEANUP_EXCLUDES ]]; then
      debug "Skipping prospect $prospect"
      continue
    fi

    if [[ $(cat "$prospect" | jq '.ProspectInfo.AssociatedMembers | length') -eq 0 && $(find "$prospect" -type f -mmin +$CLEANUP_DAYS) ]]; then
      local filename
      filename=$(basename -- "$prospect")

      if [[ $CLEANUP_DELETE_BACKUPS == true ]]; then
        info "remove backups from $filename"
        rm -f "$data_path/Saved/PlayerData/DedicatedServer/Prospects/${filename%.*}"*.backup
      fi

      info "moving prospect $filename to prune folder $CLEANUP_PRUNE_FOLDER"
      mv -f "$data_path/Saved/PlayerData/DedicatedServer/Prospects/${filename%.*}"* "$data_path/Saved/PlayerData/DedicatedServer/$CLEANUP_PRUNE_FOLDER/"
    fi
  done
  IFS="$OIFS"
}

main
