#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/defaults"

main() {
  info "Force Icarus update"
  rm $version_file_path

  debug "Removing $install_path/$steamapp_path"
  rm -rf $install_path/$steamapp_path

  supervisorctl start icarus-updater
}

main
