#!/bin/bash
. "$(dirname "$0")/common"

icarus_server_pid=-1
timeout=29
kill_signal=TERM

cd "$install_path" || fatal "Could not cd $install_path"
icarus_server="$install_path/$icarus_binary_path"

main() {
    wait_for_server_download
    run_server
}

wait_for_server_download() {
    while :; do
        if [ -f "$icarus_server" ]; then
            break
        else
            debug "icarus Server is not yet downloaded - waiting"
            sleep 7
        fi
    done
}

run_server() {
    info "Running icarus Server"
    debug "Server config -SteamServerName=${SERVERNAME:-ICARUS Server} -PORT=${PORT:-17777} -QueryPort=${QUERYPORT:-27015}"

    info "bootstrap wine"
    WINEPREFIX=/home/icarus/ WINEARCH=win64 WINEPATH=$install_path wineboot --init > /dev/null 2>&1

    initIcarusConfig

    chmod +x "$icarus_server"
    wine "$icarus_server" -Log -UserDir='C:\icarus' -SteamServerName="${SERVERNAME:-ICARUS Server}" -PORT="${PORT:-17777}" -QueryPort="${QUERYPORT:-27015}"
    icarus_server_pid=$!
    echo $icarus_server_pid > "$icarus_server_pidfile"

    wait $icarus_server_pid
    debug "icarus server with PID $icarus_server_pid stopped"

    cleanup
    info "Shutdown complete"
    exit 0
}

cleanup() {
    clear_lock "$icarus_server_pidfile"
}

shutdown() {
    debug "Received signal to shut down icarus-server"
    if [ $icarus_server_pid -eq -1 ]; then
        debug "icarus server is not running yet - aborting startup"
        exit
    fi
    info "Shutting down icarus server with PID $icarus_server_pid"
    kill -INT $icarus_server_pid
    shutdown_timeout=$(($(date +%s)+timeout))
    while [ -d "/proc/$icarus_server_pid" ]; do
        if [ "$(date +%s)" -gt $shutdown_timeout ]; then
            shutdown_timeout=$(($(date +%s)+timeout))
            warn "Timeout while waiting for server to shut down - sending SIG$kill_signal to PID $icarus_server_pid"
            kill -$kill_signal $icarus_server_pid
            case "$kill_signal" in
                INT)
                    kill_signal=TERM
                    ;;
                *)
                    kill_signal=KILL
            esac
        fi
        debug "Waiting for icarus Server with PID $icarus_server_pid to shut down"
        sleep 6
    done
}

initIcarusConfig() {
  info Setting Steam Async Timeout value in Engine.ini to echo "${STEAM_ASYNC_TIMEOUT:-60}"
  configPath='/home/icarus/.wine/drive_c/icarus/Saved/Config/WindowsServer'
  if [[ ! -e ${configPath}/Engine.ini ]]; then
    mkdir -p ${configPath}
    touch ${configPath}/Engine.ini
  fi

  if ! grep -Fxq "[OnlineSubsystemSteam]" ${configPath}/Engine.ini
  then
      echo '[OnlineSubsystemSteam]' >> ${configPath}/Engine.ini
      echo 'AsyncTaskTimeout=' >> ${configPath}/Engine.ini
  fi

  sedCommand='/AsyncTaskTimeout=/c\AsyncTaskTimeout='${STEAM_ASYNC_TIMEOUT:-60}
  sed -i "${sedCommand}" ${configPath}/Engine.ini
}

trap shutdown SIGINT SIGTERM
main
