name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: CI-${{ github.ref }}

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    with:
      image-name: icarus-server
      image-tag: dev
