name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
      - LICENSE
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency: CI-${{ github.ref }}

jobs:
  build-wine-stable:
    uses: mornedhels/workflow-center-public/.github/workflows/docker-build.yml@main
    with:
      image-name: icarus-server
      image-tag: dev
      scan-category: dev-wine
    secrets:
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  build-wine-staging:
    uses: mornedhels/workflow-center-public/.github/workflows/docker-build.yml@main
    with:
      image-name: icarus-server
      image-tag: dev-wine-staging
      scan-category: dev-wine-staging
      build-args: |
        WINE_BRANCH=staging
    secrets:
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
