name: Docker Scout Scan

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  docker-scout-scan-latest:
    uses: mornedhels/workflow-center-public/.github/workflows/docker-scout.yml@main
    with:
      image-name: icarus-server
      scan-category: wine-latest
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  docker-scout-scan-dev:
    uses: mornedhels/workflow-center-public/.github/workflows/docker-scout.yml@main
    with:
      image-name: icarus-server
      image-tag: dev
      scan-category: dev-wine
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}