name: PR-Automation

on:
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    permissions:
      contents: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge ${{github.event.pull_request.html_url}} --auto --merge
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
